const messageConstants = {
  mobileNumberDoesNotExists: 'Mobile number does not exist.',
  maximumOTPAttemptsReached: 'Maximum OTP Attempts Reached. Please request a new OTP or contact support.',
  invalidOTP: 'Invalid OTP',
  otpEntryHasExpired: "Time's Up! Your OTP entry has expired. Request a new OTP to complete verification.",
  yourAccountHasBeenLoggedOut: 'We regret any inconvenience caused. Your session is cleared, and you have been logged out. Please log in again.',
  permissionDeniedForScanQR: 'Permission denied for scanning QR',
  invalidQR: 'Invalid QR',
  bikeIsALreadyBookedScanAnother: 'This eVegah bike is currently booked. Please scan the QR code of another available bike.',
  pleaseEnterValidEmail: 'Please enter valid email',
  minimumAgeToUseTheApplication: 'The minimum age to use the eVegah application is 13 years. Thank you for understanding.',
  pleaseEnterWalletAmount: 'Please enter wallet amount.',
  pleaseEnterValidWalletAmount: 'Please Enter Valid Wallet amount.',
  paymentCancelled: 'Your payment is cancelled.',
  defaultAvailabilityTimeBetweenScanQRandStartRideExpired: 'Oops! The default availability time between scanning the QR code and starting your ride has expired. Please scan the QR code again to begin your journey.',
  wantToEndRide: 'Do you really want to end your ride?',
  wantToTempLock: 'Do you really want to temporary lock your vehicle?',
  wantToUnlock: 'Do you really want to unlock your vehicle?',
  wantToTurnOnLight: 'Do you want to turn on the light?',
  wantToTurnOffLight: 'Do you want to turn off the light?',
  canNotTurnOnOffTheLight: "Light On/Off Unavailable: You can't turn on/off vehicle's light as there is no active ride.",
  youHaveBeenLoggedOut: 'You have been logged out as your session has expired. Please log in again to continue.',
  unableToTemporaryLockYourRide: 'Your lock request has timed out. Unable to lock your ride.',
  unableToUnlockYourRide: 'Your unlock request has timed out. Unable to unlock your ride.',
  unableToTurnOnVehicleLight: 'Your light on request has timed out. Unable to turn on your vehicle light.',
  unableToTurnOffVehicleLight: 'Your light off request has timed out. Unable to turn off your vehicle light.',
  yourRideHasBeenCancelled: "Unfortunately, your ride has been canceled as it appears that your ride is currently occupied or busy. Feel free to request a new ride when you\'re available.",
  agreedToTermsAndCond: 'Before you proceed, kindly review and agree to our terms and conditions. Your acceptance is important to us.',
  fetchingEvegahZones: "We're locating eVegah zones around your current location. Hang tight!",
  noZonesFound: 'No eVegah zones found in the specified location. Explore other areas for available zones.',
  mandatoryRating: 'Oops! It seems you forgot to rate your experience. Kindly provide a rating before submitting your feedback.',
  thanksForFeedback: 'Thank you for sharing your feedback! Your insights are invaluable to us and contribute to making our services even better.',
  cameraPermissionMessage: 'Enable camera permissions in your app settings to activate Scan QR feature.',
  locationPermissionMessage: 'Enable location permissions in your app settings to activate Map feature.',
  locationPermissionDeniedMessage: 'Location access helps us show nearby eVegah zones and improve your ride experience. Please enable location in your device settings to use the map and find vehicles.',
  locationFetchTimeout: 'Getting your location is taking longer than expected. Please ensure GPS is on and try again.',
  locationGpsDisabled: 'Location unavailable. Please turn on GPS/Location services and try again.',
};

export default messageConstants;